import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import "./fonts.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sportingGrotesque = localFont({
  src: [
    {
      path: "../assets/fonts/SportingGrotesque-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/SportingGrotesque-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-sporting-grotesque",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          href="/fonts/SportingGrotesque-Bold.otf"
          as="font"
          type="font/otf"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/SportingGrotesque-Regular.otf"
          as="font"
          type="font/otf"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sportingGrotesque.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
